### ISSUE TITLE
有可能把确诊和无症状区分开吗？

### ISSUE THREAD

**Issue by standard-outlier** [luckydzp/COVID-19-AddrInShangHai#1]
看到有一些数据可以把确诊和无症状分开，比如这个[可视化项目](https://xenofex.github.io/covid-shanghai-viz/)

不过是在区的 Level，不知您这边的可以做到吗？

**Comment by standard-outlier** [comment]
另外一个小建议，直接做成 csv 会比较方便使用。

**Comment by luckydzp** [comment]
> 看到有一些数据可以把确诊和无症状分开，比如这个[可视化项目](https://xenofex.github.io/covid-shanghai-viz/)
> 
> 不过是在区的 Level，不知您这边的可以做到吗？

你好，官方数据，只在区的层面报告了确诊有无症状，没有精确到某个地址。这个无法实现的。

**Comment by luckydzp** [comment]
> 
excel 可以导出 csv 吧。不过为了防止数据篡改，我增加了文档保护。也是担心官方数据被篡改。
